project:
  type: website

website:
  title: "ISSS608 VAA"
  navbar:
    left:
      - text: Hands-on Exercise
        menu: 
          - text: Hands-on Exercise 1
            href: Hands_on_Ex1/Hands_on_Ex1.qmd
          - text: Hands-on Exercise 2
            href: Hands_on_Ex2/Hands_on_Ex2.qmd
          - text: Hands-on Exercise 3
            href: Hands_on_Ex3/Hands_on_Ex3.qmd
          - text: Hands-on Exercise 4
          - text: Hands-on Exercise 5
            href: Hands_on_Ex5/Hands_on_Ex5.qmd
            
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 1
            href: Inclass_Ex1/Inclass_Ex1.qmd
          - text: In-class Exercise 2
            href: Inclass_Ex2/Inclass_Ex2.qmd
          - text: In-class Exercise 3
            href: Inclass_Ex3/Inclass_Ex3.qmd
          - text: In-class Exercise 4
            href: Inclass_Ex4/Inclass_Ex4.qmd
          - text: In-class Exercise 5
            href: Inclass_Ex5/Inclass_Ex5.qmd
            
      - text: Take-home Exercise
        menu:
          - text: Take-home Exercise 1
            href: Take-home_Ex1/Take-home_Ex1.qmd
          - text: Take-home Exercise 2
            href: Take-home_Ex2/Take-home_Ex2.qmd
          - text: Take-home Exercise 3
            href: Take-home_Ex3/Take-home_Ex3.qmd

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

